name: Build and Deploy to GitHub Pages

on:
  # Runs on pushes to the main or master branch
  push:
    branches:
      - master
      - main

  # Allows you to manually run the workflow from the Actions tab
  workflow_dispatch:

# Set permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one deployment runs at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # or the version your project requires

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project using Webpack
      - name: Build the project
        run: npm run build

      # Upload the build output as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist  # This is your build output directory

  # Deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}